name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  host-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Dependencies & GoogleTest
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libgtest-dev
        cd /usr/src/googletest
        sudo cmake .
        sudo make
        sudo make install

    - name: Install RISC-V Toolchain and QEMU
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-riscv64-linux-gnu g++-riscv64-linux-gnu qemu-user qemu-user-static

    - name: Build and Run All Tests
      run: make test RV_CXX=riscv64-linux-gnu-g++
